# Generated by Django 4.1.2 on 2022-12-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_ingredient_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(null=True, upload_to='media/static/media'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to='media/static/media'),
        ),
    ]
