# Generated by Django 4.1.2 on 2022-12-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_cuisine_image_alter_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.IntegerField()),
                ('fuleType', models.IntegerField()),
                ('owner', models.TextField()),
            ],
        ),
    ]
