# Generated by Django 4.1.2 on 2022-12-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='carType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='fuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='carType',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuleType',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='car',
            name='carType',
            field=models.ManyToManyField(related_name='type', to='backend.cartype'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuleType',
            field=models.ManyToManyField(related_name='type', to='backend.fueltype'),
        ),
    ]
