# Generated by Django 4.1.2 on 2022-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_cartype_fueltype_remove_dish_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='carType',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuleType',
        ),
        migrations.AddField(
            model_name='car',
            name='carType',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuleType',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
