# Generated by Django 4.1.2 on 2022-12-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_car_cartype_remove_car_fuletype_car_cartype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='brand',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fueltype',
            name='name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fueltype',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='car',
            name='carType',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuleType',
        ),
        migrations.AddField(
            model_name='car',
            name='carType',
            field=models.ManyToManyField(related_name='type', to='backend.cartype'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuleType',
            field=models.ManyToManyField(related_name='type', to='backend.fueltype'),
        ),
    ]
