# Generated by Django 4.1.2 on 2022-12-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_cartype_brand_fueltype_name_fueltype_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter', models.IntegerField()),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.FloatField()),
                ('car', models.ManyToManyField(related_name='userCar', to='backend.car')),
                ('payed', models.ManyToManyField(related_name='methods', to='backend.payments')),
            ],
        ),
    ]
