# Generated by Django 4.1.2 on 2022-12-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_order_car_order_cartype_order_fueltype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extraService',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
