# Generated by Django 4.1.2 on 2023-02-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_pdata_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdata',
            name='target',
            field=models.IntegerField(null=True),
        ),
    ]
