# Generated by Django 4.1.2 on 2023-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_pdata_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.IntegerField()),
                ('Disable', models.IntegerField()),
                ('ResidantDistance', models.IntegerField()),
                ('HasInfection', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pdata',
        ),
    ]
