# Generated by Django 4.1.4 on 2024-02-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_stuinfo_delete_pdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='transcriptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeURL', models.TextField()),
                ('transcript', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='stuInfo',
        ),
    ]
