# Generated by Django 4.1.4 on 2024-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_transcriptmodel_delete_stuinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('A1', models.TextField()),
                ('A2', models.TextField()),
                ('A3', models.TextField()),
                ('A4', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='transcriptmodel',
            name='transcriptSummary',
            field=models.TextField(null=True),
        ),
    ]
