# Generated by Django 4.1.4 on 2024-03-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_questionmodel_transcriptmodel_transcriptsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionModel',
        ),
    ]
