# Generated by Django 4.1.4 on 2024-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_delete_questionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptmodel',
            name='Questions',
            field=models.JSONField(null=True),
        ),
    ]
