# Generated by Django 5.2.12 on 2026-05-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_transcriptmodel_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptmodel',
            name='Questions',
        ),
    ]
